services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nahuel
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo/:/data/db
    ports:
      - 27017:27017
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432